version: "3.8"

services:

  app:
    build: .
    restart: always
    container_name: api
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  mongo:
    image: mongo
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

