FROM python:3.7-alpine
# directory for work
WORKDIR /app
# configuration enviroment variables
RUN apk add --no-cache  musl-dev linux-headers  build-base 
# Copy requirements to docker container
COPY requirements.txt requirements.txt
# Install requirements on docker container
RUN pip3 install -r requirements.txt
COPY . .
CMD ["python3", "aux.py"]
